name: Compile ESP32 Project

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

env:
  ARDUINO_CLI_VERSION: "2.0.0"
  ESP32_CORE_VERSION: "2.0.11"

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo "$(pwd)/bin" >> $GITHUB_PATH
        
    - name: Configure Arduino CLI
      run: |
        arduino-cli config init --overwrite
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        
    - name: Install ESP32 core
      run: |
        arduino-cli core install esp32:esp32@${{ env.ESP32_CORE_VERSION }} --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        
    - name: Install required libraries
      run: |
        arduino-cli lib install "ArduinoJson"
        arduino-cli lib install "WebServer"
        arduino-cli lib install "DNSServer"
        arduino-cli lib install "WiFiManager"
        arduino-cli lib install "AsyncTCP"
        arduino-cli lib install "ESP Async WebServer"
        arduino-cli lib install "Ticker"
        
    - name: List installed boards and libraries
      run: |
        arduino-cli core list
        arduino-cli lib list
        
    - name: Compile for ESP32 Dev Module
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 bara1.ino --verbose
        echo "✅ Compilation successful for ESP32 Dev Module"
        
    - name: Compile for NodeMCU-32S
      run: |
        arduino-cli compile --fqbn esp32:esp32:nodemcu-32s bara1.ino --verbose
        echo "✅ Compilation successful for NodeMCU-32S"
        
    - name: Compile for WEMOS LOLIN D32
      run: |
        arduino-cli compile --fqbn esp32:esp32:d32 bara1.ino --verbose
        echo "✅ Compilation successful for WEMOS LOLIN D32"
        
    - name: Upload compilation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-firmware
        path: |
          build/
        retention-days: 7
